import {
  AlertTriangle,
  ArrowLeft,
  Braces,
  CheckCircle2,
  Database,
  FileJson,
  type LucideIcon,
  ShieldAlert,
} from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { AppShell } from "@/components/app-shell";
import { SeverityBadge, StatusBadge } from "@/components/status-badge";
import { parseAebTarget } from "@/lib/aeb";
import { getPayloadPreviewForApi } from "@/lib/api/capsule-service";
import { prisma } from "@/lib/db/prisma";
import { getCapsuleDetail } from "@/lib/demo/dashboard-data";
import { formatDateTime, formatStatus, formatTarget } from "@/lib/ui/format";

export const dynamic = "force-dynamic";

type PayloadPreviewPageProps = {
  params: Promise<{ id: string; target: string }>;
};

export default async function PayloadPreviewPage({
  params,
}: PayloadPreviewPageProps) {
  const { id, target } = await params;
  const parsedTarget = parseAebTarget(target);

  if (!parsedTarget) {
    notFound();
  }

  const capsule = await getCapsuleDetail(id);

  if (!capsule) {
    notFound();
  }

  const preview = await getPayloadPreviewForApi(prisma, capsule.id, parsedTarget);
  const apiUrl = `/api/capsules/${capsule.id}/payload/${parsedTarget}`;

  return (
    <AppShell>
      <main className="mx-auto w-full max-w-7xl px-5 py-8">
        <div className="flex flex-col gap-3 border-b border-slate-200 pb-6 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <Link
              href={`/capsules/${capsule.id}`}
              className="inline-flex items-center gap-2 text-sm font-semibold text-slate-700 hover:text-slate-950"
            >
              <ArrowLeft aria-hidden="true" size={16} />
              Back to capsule
            </Link>
            <h1 className="mt-4 text-3xl font-semibold text-slate-950">
              Payload Preview
            </h1>
            <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">
              AEB-compatible payload preview for {formatTarget(parsedTarget)}.
              This is generated by a mock AEB adapter and does not connect to
              external AEB APIs.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <StatusBadge size="md" status={preview.readinessStatus} />
            <Link
              href={apiUrl}
              className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-slate-300 px-4 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
            >
              <FileJson aria-hidden="true" size={16} />
              Open API JSON
            </Link>
          </div>
        </div>

        <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <MetricCard
            label="Capsule"
            value={capsule.capsuleNumber}
            detail={capsule.title}
            icon={Database}
          />
          <MetricCard
            label="Readiness"
            value={formatStatus(preview.readinessStatus)}
            detail={`${preview.blockingIssues.length} blockers, ${preview.warnings.length} warnings`}
            icon={CheckCircle2}
          />
          <MetricCard
            label="Source refs"
            value={String(preview.sourceFieldRefs.length)}
            detail="Extracted fields carried into the preview"
            icon={Braces}
          />
          <MetricCard
            label="Generated"
            value={formatDateTime(new Date(preview.generatedAt))}
            detail="Local demo timestamp"
            icon={FileJson}
          />
        </section>

        <section className="mt-6 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
          <Panel title="Validation" icon={ShieldAlert}>
            {preview.blockingIssues.length === 0 &&
            preview.warnings.length === 0 ? (
              <p className="p-5 text-sm leading-6 text-slate-600">
                No validation issues found for this AEB-ready payload preview.
              </p>
            ) : (
              <div className="divide-y divide-slate-200">
                {preview.blockingIssues.map((issue) => (
                  <IssueRow key={`blocking-${issue.code}`} issue={issue} severity="blocking" />
                ))}
                {preview.warnings.map((issue) => (
                  <IssueRow key={`warning-${issue.code}`} issue={issue} severity="warning" />
                ))}
              </div>
            )}
          </Panel>

          <Panel title="Source Field References" icon={AlertTriangle}>
            {preview.sourceFieldRefs.length === 0 ? (
              <p className="p-5 text-sm leading-6 text-slate-600">
                No extracted source fields are available for this preview.
              </p>
            ) : (
              <div className="max-h-[420px] overflow-auto">
                <table className="w-full min-w-[720px] text-left text-sm">
                  <thead className="bg-slate-50 text-xs uppercase tracking-[0.12em] text-slate-500">
                    <tr>
                      <th className="px-4 py-3 font-semibold">Field</th>
                      <th className="px-4 py-3 font-semibold">Value</th>
                      <th className="px-4 py-3 font-semibold">Confidence</th>
                      <th className="px-4 py-3 font-semibold">Source</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200">
                    {preview.sourceFieldRefs.map((ref) => (
                      <tr key={`${ref.fieldKey}-${ref.sourceRef}`}>
                        <td className="px-4 py-3 font-semibold text-slate-950">
                          {ref.label}
                        </td>
                        <td className="px-4 py-3 text-slate-700">{ref.value}</td>
                        <td className="px-4 py-3 text-slate-700">
                          {Math.round(ref.confidence * 100)}%
                        </td>
                        <td className="px-4 py-3 text-slate-700">
                          {ref.sourceRef}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </Panel>
        </section>

        <Panel title="AEB-Compatible JSON Preview" icon={FileJson}>
          <pre className="max-h-[720px] overflow-auto bg-slate-950 p-5 text-xs leading-6 text-slate-100">
            {JSON.stringify(preview, null, 2)}
          </pre>
        </Panel>
      </main>
    </AppShell>
  );
}

function MetricCard({
  label,
  value,
  detail,
  icon: Icon,
}: {
  label: string;
  value: string;
  detail: string;
  icon: LucideIcon;
}) {
  return (
    <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">
            {label}
          </p>
          <p className="mt-2 text-lg font-semibold text-slate-950">{value}</p>
        </div>
        <Icon aria-hidden="true" className="text-slate-400" size={20} />
      </div>
      <p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">
        {detail}
      </p>
    </div>
  );
}

function Panel({
  title,
  icon: Icon,
  children,
}: {
  title: string;
  icon: LucideIcon;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-6 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center gap-2 border-b border-slate-200 px-5 py-4">
        <Icon aria-hidden="true" className="text-slate-500" size={18} />
        <h2 className="text-base font-semibold text-slate-950">{title}</h2>
      </div>
      {children}
    </section>
  );
}

function IssueRow({
  issue,
  severity,
}: {
  issue: { code: string; message: string; fieldKey?: string; sourceRef?: string };
  severity: "warning" | "blocking";
}) {
  return (
    <div className="p-5">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="font-semibold text-slate-950">{issue.code}</p>
          <p className="mt-1 text-sm leading-6 text-slate-600">
            {issue.message}
          </p>
        </div>
        <SeverityBadge severity={severity} />
      </div>
      {issue.sourceRef ? (
        <p className="mt-2 text-xs uppercase tracking-[0.12em] text-slate-500">
          Source: {issue.sourceRef}
        </p>
      ) : null}
    </div>
  );
}
