import type { EvidenceCapsuleWithRelations } from "@/lib/domain/types";

const now = new Date("2026-04-30T10:00:00.000Z");
const demoDate = (value: string) => new Date(value);

const auditTimelineDates = {
  cleanBrokerHandover: {
    created: demoDate("2026-04-28T07:14:00.000Z"),
    documentsAnalyzed: demoDate("2026-04-28T07:17:00.000Z"),
    readinessComputed: demoDate("2026-04-28T07:18:00.000Z"),
    tasksCreated: demoDate("2026-04-28T07:18:30.000Z"),
    packetArchived: demoDate("2026-04-28T07:19:00.000Z"),
  },
  weightMismatch: {
    created: demoDate("2026-04-27T12:02:00.000Z"),
    documentsAnalyzed: demoDate("2026-04-27T12:05:00.000Z"),
    readinessComputed: demoDate("2026-04-27T12:06:00.000Z"),
    tasksCreated: demoDate("2026-04-27T12:06:30.000Z"),
    contradictionDetected: demoDate("2026-04-27T12:07:00.000Z"),
    taskEscalated: demoDate("2026-04-30T09:42:00.000Z"),
  },
  missingOrigin: {
    created: demoDate("2026-04-27T13:24:00.000Z"),
    documentsAnalyzed: demoDate("2026-04-27T13:27:00.000Z"),
    readinessComputed: demoDate("2026-04-27T13:29:00.000Z"),
    tasksCreated: demoDate("2026-04-27T13:29:30.000Z"),
    missingEvidenceDetected: demoDate("2026-04-27T13:30:00.000Z"),
    supplierFollowUpQueued: demoDate("2026-04-29T08:15:00.000Z"),
  },
  expiredEndUse: {
    created: demoDate("2026-04-26T08:48:00.000Z"),
    documentsAnalyzed: demoDate("2026-04-26T08:51:00.000Z"),
    readinessComputed: demoDate("2026-04-26T08:53:00.000Z"),
    tasksCreated: demoDate("2026-04-26T08:54:00.000Z"),
    documentExpired: demoDate("2026-04-26T08:54:30.000Z"),
    customerRequestStarted: demoDate("2026-04-30T08:08:00.000Z"),
  },
  missingExportParameter: {
    created: demoDate("2026-04-29T07:35:00.000Z"),
    documentsAnalyzed: demoDate("2026-04-29T07:39:00.000Z"),
    readinessComputed: demoDate("2026-04-29T07:41:00.000Z"),
    tasksCreated: demoDate("2026-04-29T07:42:00.000Z"),
    missingEvidenceDetected: demoDate("2026-04-29T07:43:00.000Z"),
    engineeringRequestQueued: demoDate("2026-04-30T13:12:00.000Z"),
  },
};

export const demoEvidenceCapsules: EvidenceCapsuleWithRelations[] = [
  {
    id: "cap_clean_broker_handover",
    capsuleNumber: "CAP-2026-0001",
    objectType: "shipment",
    title: "Industrial valve shipment ready for broker handover",
    customerName: "Nordline Components AB",
    destinationCountry: "Sweden",
    incoterm: "DAP Gothenburg",
    status: "ready",
    overallReadinessScore: 96,
    createdAt: auditTimelineDates.cleanBrokerHandover.created,
    updatedAt: auditTimelineDates.cleanBrokerHandover.packetArchived,
    sourceDocuments: [
      {
        id: "doc_0001_invoice",
        capsuleId: "cap_clean_broker_handover",
        type: "commercialInvoice",
        filename: "invoice-inv-2026-4288.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0001/invoice.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0001_packing",
        capsuleId: "cap_clean_broker_handover",
        type: "packingList",
        filename: "packing-list-pl-2026-4288.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0001/packing-list.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0001_erp",
        capsuleId: "cap_clean_broker_handover",
        type: "erpExport",
        filename: "erp-export-4288.xlsx",
        mimeType:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        mockPath: "/mock/evidence/cap-2026-0001/erp-export.xlsx",
        uploadedAt: now,
      },
      {
        id: "doc_0001_datasheet",
        capsuleId: "cap_clean_broker_handover",
        type: "technicalDatasheet",
        filename: "datasheet-industrial-valve-vx2.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0001/datasheet.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0001_end_use",
        capsuleId: "cap_clean_broker_handover",
        type: "endUseStatement",
        filename: "end-use-statement-nordline-2026.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0001/end-use.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0001_supplier",
        capsuleId: "cap_clean_broker_handover",
        type: "supplierEvidence",
        filename: "supplier-origin-and-license-evidence.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0001/supplier-evidence.pdf",
        uploadedAt: now,
      },
    ],
    extractedFields: [
      {
        id: "field_0001_invoice_value",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "invoice_value",
        label: "Invoice value",
        value: "18420 EUR",
        normalizedValue: "18420",
        confidence: 0.98,
        sourceRef: "invoice-inv-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_gross_weight",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_packing",
        fieldKey: "gross_weight_kg",
        label: "Gross weight",
        value: "892 kg",
        normalizedValue: "892",
        confidence: 0.97,
        sourceRef: "packing-list-pl-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_net_weight",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_packing",
        fieldKey: "net_weight_kg",
        label: "Net weight",
        value: "846 kg",
        normalizedValue: "846",
        confidence: 0.96,
        sourceRef: "packing-list-pl-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_hs_code",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "hs_code",
        label: "HS code",
        value: "8481.80",
        normalizedValue: "848180",
        confidence: 0.94,
        sourceRef: "invoice-inv-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_origin",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_supplier",
        fieldKey: "country_of_origin",
        label: "Country of origin",
        value: "Germany",
        normalizedValue: "DE",
        confidence: 0.95,
        sourceRef: "supplier-origin-and-license-evidence.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_exporter",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "exporter",
        label: "Exporter",
        value: "AeroValve Systems GmbH",
        normalizedValue: "AeroValve Systems GmbH",
        confidence: 0.99,
        sourceRef: "invoice-inv-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_exporter_address",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "exporter_address",
        label: "Exporter address",
        value: "Industriestrasse 18, 28199 Bremen, Germany",
        normalizedValue: "Industriestrasse 18, 28199 Bremen, Germany",
        confidence: 0.98,
        sourceRef: "invoice-inv-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_consignee",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "consignee",
        label: "Consignee",
        value: "Nordline Components AB",
        normalizedValue: "Nordline Components AB",
        confidence: 0.99,
        sourceRef: "invoice-inv-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_consignee_address",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "consignee_address",
        label: "Consignee address",
        value: "Terminalvagen 12, 418 34 Gothenburg, Sweden",
        normalizedValue: "Terminalvagen 12, 418 34 Gothenburg, Sweden",
        confidence: 0.98,
        sourceRef: "invoice-inv-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_destination",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_erp",
        fieldKey: "destination_country",
        label: "Destination country",
        value: "Sweden",
        normalizedValue: "Sweden",
        confidence: 0.99,
        sourceRef: "erp-export-4288.xlsx row 2",
        createdAt: now,
      },
      {
        id: "field_0001_currency",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "currency",
        label: "Currency",
        value: "EUR",
        normalizedValue: "EUR",
        confidence: 0.99,
        sourceRef: "invoice-inv-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_line_items",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_invoice",
        fieldKey: "line_item_count",
        label: "Line items",
        value: "4",
        normalizedValue: "4",
        confidence: 0.96,
        sourceRef: "invoice-inv-2026-4288.pdf page 2",
        createdAt: now,
      },
      {
        id: "field_0001_classification_status",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_supplier",
        fieldKey: "classification_evidence_status",
        label: "Classification evidence status",
        value: "Approved classification evidence on file",
        normalizedValue: "approved",
        confidence: 0.94,
        sourceRef: "supplier-origin-and-license-evidence.pdf page 2",
        createdAt: now,
      },
      {
        id: "field_0001_origin_evidence",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_supplier",
        fieldKey: "origin_evidence",
        label: "Origin evidence",
        value: "Supplier declaration valid through 2026",
        normalizedValue: "valid",
        confidence: 0.94,
        sourceRef: "supplier-origin-and-license-evidence.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_product_description",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_datasheet",
        fieldKey: "product_description",
        label: "Product description",
        value: "Stainless steel industrial control valves for process equipment",
        normalizedValue:
          "Stainless steel industrial control valves for process equipment",
        confidence: 0.96,
        sourceRef: "datasheet-industrial-valve-vx2.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_product_attributes",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_datasheet",
        fieldKey: "product_attributes",
        label: "Product attributes",
        value: "Valve body material 316L stainless steel; max pressure 40 bar",
        normalizedValue:
          "Valve body material 316L stainless steel; max pressure 40 bar",
        confidence: 0.95,
        sourceRef: "datasheet-industrial-valve-vx2.pdf page 2",
        createdAt: now,
      },
      {
        id: "field_0001_technical_parameters_complete",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_datasheet",
        fieldKey: "technical_parameters_complete",
        label: "Technical parameters complete",
        value: "true",
        normalizedValue: "true",
        confidence: 0.93,
        sourceRef: "datasheet-industrial-valve-vx2.pdf page 2",
        createdAt: now,
      },
      {
        id: "field_0001_end_user",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_end_use",
        fieldKey: "end_user",
        label: "End user",
        value: "Nordline Components AB",
        normalizedValue: "Nordline Components AB",
        confidence: 0.97,
        sourceRef: "end-use-statement-nordline-2026.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_end_user_address",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_end_use",
        fieldKey: "end_user_address",
        label: "End user address",
        value: "Terminalvagen 12, 418 34 Gothenburg, Sweden",
        normalizedValue: "Terminalvagen 12, 418 34 Gothenburg, Sweden",
        confidence: 0.97,
        sourceRef: "end-use-statement-nordline-2026.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_end_use",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_end_use",
        fieldKey: "end_use",
        label: "End use",
        value: "Maintenance of industrial water treatment equipment",
        normalizedValue: "maintenance of industrial water treatment equipment",
        confidence: 0.96,
        sourceRef: "end-use-statement-nordline-2026.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_risk_questionnaire_status",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_end_use",
        fieldKey: "risk_questionnaire_status",
        label: "Risk questionnaire status",
        value: "Current",
        normalizedValue: "current",
        confidence: 0.92,
        sourceRef: "end-use-statement-nordline-2026.pdf page 2",
        createdAt: now,
      },
      {
        id: "field_0001_risk_questionnaire_date",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_end_use",
        fieldKey: "risk_questionnaire_date",
        label: "Risk questionnaire date",
        value: "2026-02-12",
        normalizedValue: "2026-02-12",
        confidence: 0.92,
        sourceRef: "end-use-statement-nordline-2026.pdf page 2",
        createdAt: now,
      },
      {
        id: "field_0001_no_license_required",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_supplier",
        fieldKey: "no_license_required",
        label: "License evidence",
        value: "No license required for this demo shipment",
        normalizedValue: "no_license_required",
        confidence: 0.91,
        sourceRef: "supplier-origin-and-license-evidence.pdf page 3",
        createdAt: now,
      },
      {
        id: "field_0001_dimensions",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_packing",
        fieldKey: "dimensions",
        label: "Dimensions",
        value: "4 pallets, each 120 x 80 x 95 cm",
        normalizedValue: "4 pallets, each 120 x 80 x 95 cm",
        confidence: 0.94,
        sourceRef: "packing-list-pl-2026-4288.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0001_package_count",
        capsuleId: "cap_clean_broker_handover",
        sourceDocumentId: "doc_0001_packing",
        fieldKey: "package_count",
        label: "Package count",
        value: "4 pallets",
        normalizedValue: "4",
        confidence: 0.96,
        sourceRef: "packing-list-pl-2026-4288.pdf page 1",
        createdAt: now,
      },
    ],
    contradictions: [],
    missingEvidence: [],
    readinessChecks: [
      {
        id: "check_0001_broker",
        capsuleId: "cap_clean_broker_handover",
        target: "CUSTOMS_BROKER_INTEGRATION",
        status: "ready",
        score: 96,
        summary: "Ready for broker handover with aligned invoice, packing and ERP evidence.",
        details: {
          matchedDocuments: ["commercialInvoice", "packingList", "erpExport"],
          blockers: [],
        },
      },
    ],
    remediationTasks: [
      {
        id: "task_0001_archive",
        capsuleId: "cap_clean_broker_handover",
        title: "Archive broker handover packet",
        description: "Store the AEB-ready packet preview with the shipment record.",
        ownerRole: "logistics",
        status: "resolved",
        dueDate: null,
        createdAt: auditTimelineDates.cleanBrokerHandover.tasksCreated,
        updatedAt: auditTimelineDates.cleanBrokerHandover.packetArchived,
      },
    ],
    auditEvents: [
      {
        id: "audit_0001_created",
        capsuleId: "cap_clean_broker_handover",
        eventType: "capsule.created",
        message: "Evidence Capsule created from invoice, packing list and ERP export.",
        actor: "demo.seed",
        metadata: { source: "seed" },
        createdAt: auditTimelineDates.cleanBrokerHandover.created,
      },
      {
        id: "audit_0001_documents",
        capsuleId: "cap_clean_broker_handover",
        eventType: "documents.analyzed",
        message: "Six source documents analyzed and linked to extracted evidence fields.",
        actor: "extraction.deterministic",
        metadata: { sourceDocuments: 6, extractedFields: 24 },
        createdAt: auditTimelineDates.cleanBrokerHandover.documentsAnalyzed,
      },
      {
        id: "audit_0001_readiness",
        capsuleId: "cap_clean_broker_handover",
        eventType: "readiness.computed",
        message: "Broker handover readiness computed with no blocking issues.",
        actor: "readiness.rules",
        metadata: { overallReadinessScore: 96, capsuleStatus: "ready" },
        createdAt: auditTimelineDates.cleanBrokerHandover.readinessComputed,
      },
      {
        id: "audit_0001_tasks",
        capsuleId: "cap_clean_broker_handover",
        eventType: "tasks.created",
        message: "One archive task created for the ready handover packet.",
        actor: "readiness.rules",
        metadata: { tasks: 1 },
        createdAt: auditTimelineDates.cleanBrokerHandover.tasksCreated,
      },
      {
        id: "audit_0001_archived",
        capsuleId: "cap_clean_broker_handover",
        eventType: "task.resolved",
        message: "Broker handover packet archived with the shipment record.",
        actor: "logistics",
        metadata: { taskId: "task_0001_archive" },
        createdAt: auditTimelineDates.cleanBrokerHandover.packetArchived,
      },
    ],
  },
  {
    id: "cap_weight_mismatch",
    capsuleNumber: "CAP-2026-0002",
    objectType: "shipment",
    title: "Pump assembly shipment with weight mismatch",
    customerName: "Harborline Services Ltd",
    destinationCountry: "United Kingdom",
    incoterm: "FCA Hamburg",
    status: "blocked",
    overallReadinessScore: 45,
    createdAt: auditTimelineDates.weightMismatch.created,
    updatedAt: auditTimelineDates.weightMismatch.taskEscalated,
    sourceDocuments: [
      {
        id: "doc_0002_invoice",
        capsuleId: "cap_weight_mismatch",
        type: "commercialInvoice",
        filename: "invoice-inv-2026-4301.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0002/invoice.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0002_packing",
        capsuleId: "cap_weight_mismatch",
        type: "packingList",
        filename: "packing-list-pl-2026-4301.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0002/packing-list.pdf",
        uploadedAt: now,
      },
    ],
    extractedFields: [
      {
        id: "field_0002_invoice_weight",
        capsuleId: "cap_weight_mismatch",
        sourceDocumentId: "doc_0002_invoice",
        fieldKey: "gross_weight_kg",
        label: "Gross weight",
        value: "228 kg",
        normalizedValue: "228",
        confidence: 0.94,
        sourceRef: "invoice-inv-2026-4301.pdf page 1",
        createdAt: now,
      },
      {
        id: "field_0002_packing_weight",
        capsuleId: "cap_weight_mismatch",
        sourceDocumentId: "doc_0002_packing",
        fieldKey: "gross_weight_kg",
        label: "Gross weight",
        value: "282 kg",
        normalizedValue: "282",
        confidence: 0.92,
        sourceRef: "packing-list-pl-2026-4301.pdf page 1",
        createdAt: now,
      },
    ],
    contradictions: [
      {
        id: "contra_0002_weight",
        capsuleId: "cap_weight_mismatch",
        fieldKey: "gross_weight_kg",
        severity: "blocking",
        description:
          "GROSS_WEIGHT_MISMATCH: Commercial invoice and packing list show different gross weights.",
        leftSource: "invoice-inv-2026-4301.pdf page 1",
        leftValue: "228 kg",
        rightSource: "packing-list-pl-2026-4301.pdf page 1",
        rightValue: "282 kg",
      },
    ],
    missingEvidence: [],
    readinessChecks: [
      {
        id: "check_0002_broker",
        capsuleId: "cap_weight_mismatch",
        target: "CUSTOMS_BROKER_INTEGRATION",
        status: "blocked",
        score: 45,
        summary:
          "Broker handover is blocked until the gross weight mismatch is resolved.",
        details: {
          contradictionCount: 1,
          blockingGaps: 0,
        },
      },
    ],
    remediationTasks: [
      {
        id: "task_0002_weight",
        capsuleId: "cap_weight_mismatch",
        title: "Confirm shipment gross weight",
        description: "Ask logistics to reconcile invoice and packing list gross weights.",
        ownerRole: "logistics",
        status: "open",
        reasonCode: "GROSS_WEIGHT_MISMATCH",
        target: "CUSTOMS_BROKER_INTEGRATION",
        severity: "blocking",
        dismissedReason: null,
        dueDate: new Date("2026-05-03T17:00:00.000Z"),
        createdAt: auditTimelineDates.weightMismatch.tasksCreated,
        updatedAt: auditTimelineDates.weightMismatch.taskEscalated,
      },
    ],
    auditEvents: [
      {
        id: "audit_0002_created",
        capsuleId: "cap_weight_mismatch",
        eventType: "capsule.created",
        message: "Evidence Capsule created from invoice and packing list.",
        actor: "demo.seed",
        metadata: { source: "seed" },
        createdAt: auditTimelineDates.weightMismatch.created,
      },
      {
        id: "audit_0002_documents",
        capsuleId: "cap_weight_mismatch",
        eventType: "documents.analyzed",
        message: "Commercial invoice and packing list analyzed for shipment data.",
        actor: "extraction.deterministic",
        metadata: { sourceDocuments: 2, extractedFields: 2 },
        createdAt: auditTimelineDates.weightMismatch.documentsAnalyzed,
      },
      {
        id: "audit_0002_readiness",
        capsuleId: "cap_weight_mismatch",
        eventType: "readiness.computed",
        message: "Broker handover readiness computed and marked blocked.",
        actor: "readiness.rules",
        metadata: { overallReadinessScore: 45, capsuleStatus: "blocked" },
        createdAt: auditTimelineDates.weightMismatch.readinessComputed,
      },
      {
        id: "audit_0002_tasks",
        capsuleId: "cap_weight_mismatch",
        eventType: "tasks.created",
        message: "Logistics remediation task created for the weight mismatch.",
        actor: "readiness.rules",
        metadata: { tasks: 1 },
        createdAt: auditTimelineDates.weightMismatch.tasksCreated,
      },
      {
        id: "audit_0002_contradiction",
        capsuleId: "cap_weight_mismatch",
        eventType: "contradiction.detected",
        message: "Gross weight mismatch detected between invoice and packing list.",
        actor: "readiness.rules",
        metadata: { fieldKey: "gross_weight_kg" },
        createdAt: auditTimelineDates.weightMismatch.contradictionDetected,
      },
      {
        id: "audit_0002_escalated",
        capsuleId: "cap_weight_mismatch",
        eventType: "task.status.changed",
        message: "Logistics follow-up still open after broker handover review.",
        actor: "logistics",
        metadata: { taskId: "task_0002_weight", status: "open" },
        createdAt: auditTimelineDates.weightMismatch.taskEscalated,
      },
    ],
  },
  {
    id: "cap_missing_origin",
    capsuleNumber: "CAP-2026-0003",
    objectType: "shipment",
    title: "Conveyor parts missing preferential origin evidence",
    customerName: "Baltic Plant Operations",
    destinationCountry: "Norway",
    incoterm: "DAP Oslo",
    status: "blocked",
    overallReadinessScore: 54,
    createdAt: auditTimelineDates.missingOrigin.created,
    updatedAt: auditTimelineDates.missingOrigin.supplierFollowUpQueued,
    sourceDocuments: [
      {
        id: "doc_0003_invoice",
        capsuleId: "cap_missing_origin",
        type: "commercialInvoice",
        filename: "invoice-inv-2026-4319.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0003/invoice.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0003_supplier",
        capsuleId: "cap_missing_origin",
        type: "supplierEvidence",
        filename: "supplier-pack-4319.zip",
        mimeType: "application/zip",
        mockPath: "/mock/evidence/cap-2026-0003/supplier-pack.zip",
        uploadedAt: now,
      },
    ],
    extractedFields: [
      {
        id: "field_0003_preference_claim",
        capsuleId: "cap_missing_origin",
        sourceDocumentId: "doc_0003_invoice",
        fieldKey: "preference_claimed",
        label: "Preference claimed",
        value: "Yes",
        normalizedValue: "true",
        confidence: 0.9,
        sourceRef: "invoice-inv-2026-4319.pdf page 1",
        createdAt: now,
      },
    ],
    contradictions: [],
    missingEvidence: [
      {
        id: "missing_0003_origin",
        capsuleId: "cap_missing_origin",
        evidenceKey: "preferential_origin_statement",
        label: "Preferential origin statement",
        severity: "blocking",
        requiredForTarget: "CUSTOMS_MANAGEMENT",
        suggestedAction:
          "Request a current supplier declaration or remove the preference claim before handover.",
      },
    ],
    readinessChecks: [
      {
        id: "check_0003_customs",
        capsuleId: "cap_missing_origin",
        target: "CUSTOMS_MANAGEMENT",
        status: "blocked",
        score: 54,
        summary: "Preference-related customs readiness is blocked by missing origin evidence.",
        details: {
          missingEvidence: ["preferential_origin_statement"],
          legalConclusion: false,
        },
      },
    ],
    remediationTasks: [
      {
        id: "task_0003_origin",
        capsuleId: "cap_missing_origin",
        title: "Request preferential origin statement",
        description: "Ask the supplier for current preferential origin evidence.",
        ownerRole: "purchasing",
        status: "open",
        reasonCode: "MISSING_PREFERENTIAL_ORIGIN_EVIDENCE",
        target: "CUSTOMS_BROKER_INTEGRATION",
        severity: "blocking",
        dismissedReason: null,
        dueDate: new Date("2026-05-04T17:00:00.000Z"),
        createdAt: auditTimelineDates.missingOrigin.tasksCreated,
        updatedAt: auditTimelineDates.missingOrigin.supplierFollowUpQueued,
      },
    ],
    auditEvents: [
      {
        id: "audit_0003_created",
        capsuleId: "cap_missing_origin",
        eventType: "capsule.created",
        message: "Evidence Capsule created for a shipment with a preference claim.",
        actor: "demo.seed",
        metadata: { source: "seed" },
        createdAt: auditTimelineDates.missingOrigin.created,
      },
      {
        id: "audit_0003_documents",
        capsuleId: "cap_missing_origin",
        eventType: "documents.analyzed",
        message: "Invoice and supplier evidence pack analyzed for origin support.",
        actor: "extraction.deterministic",
        metadata: { sourceDocuments: 2, extractedFields: 1 },
        createdAt: auditTimelineDates.missingOrigin.documentsAnalyzed,
      },
      {
        id: "audit_0003_readiness",
        capsuleId: "cap_missing_origin",
        eventType: "readiness.computed",
        message: "Customs management readiness computed and marked blocked.",
        actor: "readiness.rules",
        metadata: { overallReadinessScore: 54, capsuleStatus: "blocked" },
        createdAt: auditTimelineDates.missingOrigin.readinessComputed,
      },
      {
        id: "audit_0003_tasks",
        capsuleId: "cap_missing_origin",
        eventType: "tasks.created",
        message: "Purchasing task created to request preferential origin evidence.",
        actor: "readiness.rules",
        metadata: { tasks: 1 },
        createdAt: auditTimelineDates.missingOrigin.tasksCreated,
      },
      {
        id: "audit_0003_missing",
        capsuleId: "cap_missing_origin",
        eventType: "missing_evidence.detected",
        message: "Preferential origin evidence is missing for a claimed preference.",
        actor: "readiness.rules",
        metadata: { evidenceKey: "preferential_origin_statement" },
        createdAt: auditTimelineDates.missingOrigin.missingEvidenceDetected,
      },
      {
        id: "audit_0003_supplier_followup",
        capsuleId: "cap_missing_origin",
        eventType: "task.status.changed",
        message: "Supplier evidence request queued with purchasing.",
        actor: "purchasing",
        metadata: { taskId: "task_0003_origin", status: "open" },
        createdAt: auditTimelineDates.missingOrigin.supplierFollowUpQueued,
      },
    ],
  },
  {
    id: "cap_expired_end_use",
    capsuleNumber: "CAP-2026-0004",
    objectType: "customerOrder",
    title: "Customer order with expired end-use statement",
    customerName: "Gulf Energy Projects LLC",
    destinationCountry: "United Arab Emirates",
    incoterm: "CIP Dubai",
    status: "blocked",
    overallReadinessScore: 49,
    createdAt: auditTimelineDates.expiredEndUse.created,
    updatedAt: auditTimelineDates.expiredEndUse.customerRequestStarted,
    sourceDocuments: [
      {
        id: "doc_0004_end_use",
        capsuleId: "cap_expired_end_use",
        type: "endUseStatement",
        filename: "end-use-statement-gulf-energy.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0004/end-use-statement.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0004_order",
        capsuleId: "cap_expired_end_use",
        type: "erpExport",
        filename: "customer-order-7721.csv",
        mimeType: "text/csv",
        mockPath: "/mock/evidence/cap-2026-0004/customer-order.csv",
        uploadedAt: now,
      },
    ],
    extractedFields: [
      {
        id: "field_0004_end_use_expiry",
        capsuleId: "cap_expired_end_use",
        sourceDocumentId: "doc_0004_end_use",
        fieldKey: "end_use_statement_expiry",
        label: "End-use statement expiry",
        value: "2026-02-15",
        normalizedValue: "2026-02-15",
        confidence: 0.96,
        sourceRef: "end-use-statement-gulf-energy.pdf page 2",
        createdAt: now,
      },
    ],
    contradictions: [],
    missingEvidence: [
      {
        id: "missing_0004_end_use",
        capsuleId: "cap_expired_end_use",
        evidenceKey: "current_end_use_statement",
        label: "Current end-use statement",
        severity: "blocking",
        requiredForTarget: "LICENSE_MANAGEMENT",
        suggestedAction: "Request a refreshed end-use statement from the customer.",
      },
    ],
    readinessChecks: [
      {
        id: "check_0004_license",
        capsuleId: "cap_expired_end_use",
        target: "LICENSE_MANAGEMENT",
        status: "blocked",
        score: 49,
        summary: "License-management readiness is blocked because the end-use statement is expired.",
        details: {
          expiredDocument: "end-use-statement-gulf-energy.pdf",
          expiryDate: "2026-02-15",
        },
      },
    ],
    remediationTasks: [
      {
        id: "task_0004_end_use",
        capsuleId: "cap_expired_end_use",
        title: "Collect updated end-use statement",
        description: "Ask sales or the customer for a current signed end-use statement.",
        ownerRole: "customer",
        status: "inProgress",
        reasonCode: "END_USE_STATEMENT_EXPIRED",
        target: "EXPORT_CONTROLS",
        severity: "blocking",
        dismissedReason: null,
        dueDate: new Date("2026-05-02T17:00:00.000Z"),
        createdAt: auditTimelineDates.expiredEndUse.tasksCreated,
        updatedAt: auditTimelineDates.expiredEndUse.customerRequestStarted,
      },
    ],
    auditEvents: [
      {
        id: "audit_0004_created",
        capsuleId: "cap_expired_end_use",
        eventType: "capsule.created",
        message: "Evidence Capsule created for customer order readiness review.",
        actor: "demo.seed",
        metadata: { source: "seed" },
        createdAt: auditTimelineDates.expiredEndUse.created,
      },
      {
        id: "audit_0004_documents",
        capsuleId: "cap_expired_end_use",
        eventType: "documents.analyzed",
        message: "End-use statement and customer order export analyzed.",
        actor: "extraction.deterministic",
        metadata: { sourceDocuments: 2, extractedFields: 1 },
        createdAt: auditTimelineDates.expiredEndUse.documentsAnalyzed,
      },
      {
        id: "audit_0004_readiness",
        capsuleId: "cap_expired_end_use",
        eventType: "readiness.computed",
        message: "License management readiness computed and marked blocked.",
        actor: "readiness.rules",
        metadata: { overallReadinessScore: 49, capsuleStatus: "blocked" },
        createdAt: auditTimelineDates.expiredEndUse.readinessComputed,
      },
      {
        id: "audit_0004_tasks",
        capsuleId: "cap_expired_end_use",
        eventType: "tasks.created",
        message: "Customer follow-up task created for a refreshed end-use statement.",
        actor: "readiness.rules",
        metadata: { tasks: 1 },
        createdAt: auditTimelineDates.expiredEndUse.tasksCreated,
      },
      {
        id: "audit_0004_expired",
        capsuleId: "cap_expired_end_use",
        eventType: "document.expired",
        message: "End-use statement date is older than the accepted demo threshold.",
        actor: "readiness.rules",
        metadata: { fieldKey: "end_use_statement_expiry" },
        createdAt: auditTimelineDates.expiredEndUse.documentExpired,
      },
      {
        id: "audit_0004_customer_request",
        capsuleId: "cap_expired_end_use",
        eventType: "task.status.changed",
        message: "Customer request moved to in progress by sales operations.",
        actor: "sales",
        metadata: { taskId: "task_0004_end_use", status: "inProgress" },
        createdAt: auditTimelineDates.expiredEndUse.customerRequestStarted,
      },
    ],
  },
  {
    id: "cap_missing_export_parameter",
    capsuleNumber: "CAP-2026-0005",
    objectType: "material",
    title: "Sensor module missing technical parameter for export-control readiness",
    customerName: "AeroMotion Systems Inc.",
    destinationCountry: "United States",
    incoterm: "EXW Munich",
    status: "blocked",
    overallReadinessScore: 41,
    createdAt: auditTimelineDates.missingExportParameter.created,
    updatedAt: auditTimelineDates.missingExportParameter.engineeringRequestQueued,
    sourceDocuments: [
      {
        id: "doc_0005_datasheet",
        capsuleId: "cap_missing_export_parameter",
        type: "technicalDatasheet",
        filename: "sensor-module-sm-44-datasheet.pdf",
        mimeType: "application/pdf",
        mockPath: "/mock/evidence/cap-2026-0005/datasheet.pdf",
        uploadedAt: now,
      },
      {
        id: "doc_0005_broker_email",
        capsuleId: "cap_missing_export_parameter",
        type: "brokerEmail",
        filename: "broker-question-sm-44.eml",
        mimeType: "message/rfc822",
        mockPath: "/mock/evidence/cap-2026-0005/broker-question.eml",
        uploadedAt: now,
      },
    ],
    extractedFields: [
      {
        id: "field_0005_temperature",
        capsuleId: "cap_missing_export_parameter",
        sourceDocumentId: "doc_0005_datasheet",
        fieldKey: "operating_temperature_range",
        label: "Operating temperature range",
        value: "-20 C to 80 C",
        normalizedValue: "-20..80 C",
        confidence: 0.89,
        sourceRef: "sensor-module-sm-44-datasheet.pdf page 3",
        createdAt: now,
      },
    ],
    contradictions: [],
    missingEvidence: [
      {
        id: "missing_0005_sampling_rate",
        capsuleId: "cap_missing_export_parameter",
        evidenceKey: "sensor_sampling_rate",
        label: "Sensor sampling rate",
        severity: "blocking",
        requiredForTarget: "EXPORT_CONTROLS",
        suggestedAction:
          "Ask engineering for the maximum sampling rate and measurement precision.",
      },
    ],
    readinessChecks: [
      {
        id: "check_0005_export",
        capsuleId: "cap_missing_export_parameter",
        target: "EXPORT_CONTROLS",
        status: "blocked",
        score: 41,
        summary:
          "Export-control readiness is blocked by a missing technical parameter.",
        details: {
          missingTechnicalParameters: ["sensor_sampling_rate"],
          conclusionMade: false,
        },
      },
    ],
    remediationTasks: [
      {
        id: "task_0005_engineering",
        capsuleId: "cap_missing_export_parameter",
        title: "Confirm sensor sampling rate",
        description: "Ask engineering to provide the maximum sampling rate for SM-44.",
        ownerRole: "engineering",
        status: "open",
        reasonCode: "MISSING_EXPORT_CONTROL_TECHNICAL_PARAMETER",
        target: "EXPORT_CONTROLS",
        severity: "blocking",
        dismissedReason: null,
        dueDate: new Date("2026-05-06T17:00:00.000Z"),
        createdAt: auditTimelineDates.missingExportParameter.tasksCreated,
        updatedAt: auditTimelineDates.missingExportParameter.engineeringRequestQueued,
      },
    ],
    auditEvents: [
      {
        id: "audit_0005_created",
        capsuleId: "cap_missing_export_parameter",
        eventType: "capsule.created",
        message: "Evidence Capsule created from datasheet and broker question.",
        actor: "demo.seed",
        metadata: { source: "seed" },
        createdAt: auditTimelineDates.missingExportParameter.created,
      },
      {
        id: "audit_0005_documents",
        capsuleId: "cap_missing_export_parameter",
        eventType: "documents.analyzed",
        message: "Technical datasheet and broker email analyzed for export-control readiness.",
        actor: "extraction.deterministic",
        metadata: { sourceDocuments: 2, extractedFields: 1 },
        createdAt: auditTimelineDates.missingExportParameter.documentsAnalyzed,
      },
      {
        id: "audit_0005_readiness",
        capsuleId: "cap_missing_export_parameter",
        eventType: "readiness.computed",
        message: "Export-controls readiness computed and marked blocked.",
        actor: "readiness.rules",
        metadata: { overallReadinessScore: 41, capsuleStatus: "blocked" },
        createdAt: auditTimelineDates.missingExportParameter.readinessComputed,
      },
      {
        id: "audit_0005_tasks",
        capsuleId: "cap_missing_export_parameter",
        eventType: "tasks.created",
        message: "Engineering task created for missing technical parameter evidence.",
        actor: "readiness.rules",
        metadata: { tasks: 1 },
        createdAt: auditTimelineDates.missingExportParameter.tasksCreated,
      },
      {
        id: "audit_0005_parameter",
        capsuleId: "cap_missing_export_parameter",
        eventType: "missing_evidence.detected",
        message: "Technical parameter required for export-control readiness is missing.",
        actor: "readiness.rules",
        metadata: { evidenceKey: "sensor_sampling_rate" },
        createdAt: auditTimelineDates.missingExportParameter.missingEvidenceDetected,
      },
      {
        id: "audit_0005_engineering_request",
        capsuleId: "cap_missing_export_parameter",
        eventType: "task.status.changed",
        message: "Engineering request queued for sensor sampling rate evidence.",
        actor: "engineering",
        metadata: { taskId: "task_0005_engineering", status: "open" },
        createdAt: auditTimelineDates.missingExportParameter.engineeringRequestQueued,
      },
    ],
  },
];

export const sampleTradeDocumentText = `
Commercial Invoice
Invoice Number: INV-2026-4288
Customer: Nordline Components AB
Destination Country: Sweden
Incoterm: DAP Gothenburg
Value: EUR 18420
Gross Weight: 892 kg
Supplier declaration: origin wording appears present but should be reviewed.
`;
